#include <bits/stdc++.h>

using namespace std;


typedef __int128_t lll; typedef long long ll; typedef long double ld;
typedef pair<int,int> pii; typedef pair<ll,ll> pll;
typedef vector<int> vi; typedef vector<ll> vll; typedef vector<pii> vpii; typedef vector<pll> vpll;

#define pb push_back
#define f first
#define s second

bool isBad(int x, int y, vector<string> &grid) {
    if (grid[x][y] == 'W') return false;
    for (int i: {-1,1}) {
        for (int j: {-1,1}) {
            if (grid[x+i][y+j] == 'W') return false;
        }
    }
    return true;
}

void solve() {
    vector<string> grid(7);
    for (string& s: grid) cin >> s;

    // odd
    auto f1 = [&] (int x, int y, vector<string> grid, int rep, int parity, auto const& f) -> int {
        for (int i = x; i < 6; ++i) {
            for (int j = (i==x ? y+1 : 1); j < 6; ++j) {

                if (grid[i][j] == 'B' and (i + j) % 2 == parity) {

                    int a = f(i, j, grid, rep, parity, f);
                    int b = 1000;

                    if (rep < 4) {
                        vector<string> newgrid(grid);
                        newgrid[i][j] = 'W';
                        b = f(i, j, newgrid, rep + 1, parity, f);
                    }

                    return min(a, b);
                }

            }
        }

        for (int i=1; i<6; ++i) {
            for (int j=1; j<6; ++j) {
                if (grid[i][j] == 'B' and (i + j) % 2 == parity and isBad(i,j,grid))
                    return 1000;
            }
        }

        return rep;
    };


//    // even
//    auto f2 = [&] (int x, int y, vector<string> grid, int rep, auto const& f) -> int {
//        for (int i = x; i < 6; ++i) {
//            for (int j = (i==x ? y+1 : 1); j < 6; ++j) {
//
//                if (grid[i][j] == 'B' and (i + j) & 1 and rep < 4) {
//                    vector<string> newgrid(grid);
//                    newgrid[i][j] = 'W';
//
//                    int a = f(i, j, grid, rep, f);
//                    int b = f(i, j, newgrid, rep + 1, f);
//
//                    return min(a, b);
//                }
//
//            }
//        }
//
//        for (int i=1; i<6; ++i) {
//            for (int j=1; j<6; ++j) {
//                if (grid[i][j] == 'B' and (i + j) & 1 and isBad(i,j,grid))
//                    return 1000;
//            }
//        }
//
//        return rep;
//    };

    cout << f1(1,0, grid, 0, 0, f1) + f1(1,0, grid, 0, 1, f1) << '\n';

}

signed main() {
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t; cin >> t;
    while (t--) {
        solve();
    }
}

/*
220
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
WWWWWWW WWWBWBW WWBWBWW WBWBWBW WWBWBWW WBWBWWW WWWWWWW
*/